[tool.isort]

# запуск isort со своими найстройки для конкретного модуля или файла
# isort some_module_name --settings isort.toml

line_length = 120  # Максимальная длина строки
# known_third_party = "flask"  # Список сторонних библиотек, которые не нужно сортировать

# sections определяет порядок, в котором импорты будут разделены в коде
#sections = [
#    "FUTURE",  # Импорты из __future__ (например, импорты для Python 2/3 совместимости)
#    "STDLIB",  # Импорты из стандартной библиотеки
#    "THIRDPARTY",  # Импорты из сторонних библиотек
#    "FIRSTPARTY",  # Импорты из вашего собственного проекта
#]

